swagger: '2.0'
info:
  title: OpenTokRTC API
  description: >-
    OpenTokRTC App, path and API description. TO-DO: Add here a general
    description of the page navigation.
  version: 1.0.0
host: opentokdemo.tokbox.com
schemes:
  - https
basePath: /
consumes:
  - application/x-www-form-urlencoded
  - application/json
produces:
  - application/json
  - text/html
x-implementation-module: serverMethods.js
x-implementation-configuration: loadConfig
paths:
  '/*':
    get:
      summary: Gets the redirect page.
      x-implemented-in: getRedirectPage
      produces:
        - 'text/html'
      description: Returns the redirect page, which includes a JavaScript redirect.
      responses:
        '200':
          description: The HTML for the redirect page
